### ISSUE TITLE
State selection should reflect Mexico if Mexico is selected

### ISSUE THREAD

**Issue by wasade** [biocore/microsetta-interface#156]
...the states should reflect Mexico rather than the US 

![Screen Shot 2021-05-27 at 1 23 52 PM](https://user-images.githubusercontent.com/474290/119892276-d467d300-beee-11eb-8944-57e1acfdf57c.png)

**Comment by antgonza** [comment]
Also note these problems:
![119892276-d467d300-beee-11eb-8944-57e1acfdf57c](https://user-images.githubusercontent.com/2014559/119904510-c07c9b00-bf07-11eb-99ce-6119147b37c1.png)

Expresar is to Express; the other 2 are still in English.
