### ISSUE TITLE
Spanish Translation Super Ticket

### ISSUE THREAD

**Issue by dhakim87** [biocore/microsetta-interface#158]
Breadcrumb:  

- [x] Probably shouldn't say Casa for Home page.  Maybe página inicial or inició?

Account Details: 

- [x] <img width="172" alt="Screen Shot 2021-05-28 at 5 00 18 PM" src="https://user-images.githubusercontent.com/26189444/120051641-3d764600-bfd6-11eb-8517-a950c7b6d8a8.png">
- [x] <img width="344" alt="Screen Shot 2021-05-28 at 5 00 38 PM" src="https://user-images.githubusercontent.com/26189444/120051646-41a26380-bfd6-11eb-9414-c219bc5418f9.png">

Consent Form (3 of 4 age variants)

- [ ] <img width="167" alt="Screen Shot 2021-05-28 at 5 01 34 PM" src="https://user-images.githubusercontent.com/26189444/120051666-60a0f580-bfd6-11eb-8f83-4bc5f55ad013.png">
- [x] Experimental Subject Bill of Rights url: https://oag.ca.gov/sites/all/files/agweb/pdfs/research/bill_of_rights.pdf

Covid Questionnaire

- [x] Blank questions:
<img width="370" alt="Screen Shot 2021-05-28 at 5 05 35 PM" src="https://user-images.githubusercontent.com/26189444/120051791-f472c180-bfd6-11eb-8014-f5936f727776.png">

Source page:

- Untranslated info from private api and None dates: 
- [x] <img width="1191" alt="Screen Shot 2021-05-28 at 5 07 04 PM" src="https://user-images.githubusercontent.com/26189444/120051848-3d2a7a80-bfd7-11eb-9ee8-0d184cef8a6d.png">
- [x] <img width="1157" alt="Screen Shot 2021-05-28 at 5 06 53 PM" src="https://user-images.githubusercontent.com/26189444/120051872-5c290c80-bfd7-11eb-9a0b-c5ce96ff4d2f.png">
- [x] <img width="531" alt="Screen Shot 2021-05-28 at 5 15 19 PM" src="https://user-images.githubusercontent.com/26189444/120052076-541d9c80-bfd8-11eb-95bc-f1a1e882d1e7.png">

Sample page:

- [x] English datepicker: Hubo un fallo al cargar el <script> con fuente “https://www-dev.ucsd.edu/static/vendor/jquery-ui-i18n/datepicker-es.js”.

Create Environmental Source page:

- [x] <img width="347" alt="Screen Shot 2021-05-28 at 5 18 34 PM" src="https://user-images.githubusercontent.com/26189444/120052164-c7271300-bfd8-11eb-817c-b4f59b01b8d6.png">

**Comment by wasade** [comment]
PENDING PENDING is in process

I was unable to recreate the english datepicker, and the translated covid questionnaire is now in.

Examining the private API items right now
