### ISSUE TITLE
Use "Account" rather than "Profile"

### ISSUE THREAD

**Issue by wasade** [biocore/microsetta-interface#179]
As part of the THDMI-MX review, it was noted that both Profile and Account is used. This was due to the original idea of having multiple profiles associated with an account, however the present use of both terms creates confusion from a communications perspective. The recommendation is to switch and standardize on the use of "Account"

**Comment by wasade** [comment]
...for the button, use "Save" rather than "Save Account"

**Comment by cassidysymons** [comment]
@wasade do you want me to tackle this along with the other interface issues?

**Comment by wasade** [comment]
That'd be great, thank you!!
