### ISSUE TITLE
Account Overview

### ISSUE THREAD

**Issue by specsdom** [biocore/microsetta-interface#20]
- Reconfiguring how to select sources on the account_overview page
- Adding success alert (only shows up after user has completed setting up account/profile)

**Assets**
[Specs on Overall Page](https://zpl.io/2p9qowQ)
[Specs on Source Selection Card](https://zpl.io/VxP5JmW)
[Specs on Explainer Card](https://zpl.io/bl5X4rP)
[Live Preview](https://www.figma.com/proto/xuTVtsQeTAaLxPC6RePkHI/Wireframes-Iteration-1?node-id=83%3A634&viewport=-2452%2C489%2C0.5&scaling=scale-down)

[Cards](https://getbootstrap.com/docs/4.4/components/card/) - For creating source selection card and explainer cards
[Alerts](https://getbootstrap.com/docs/4.0/components/alerts/) - For creating success alert

[Source Icons (Provided by Departures)](https://zpl.io/2p9qowQ)

**Comment by specsdom** [comment]
If needed, the split explainer cards can be merged into a singular card with a line in between the two paragraphs to separate them

**Comment by specsdom** [comment]
Adding profile icon is pending... still working around how to implement this

**Comment by specsdom** [comment]
Partial code available; only missing images and links

`<div class="source selection">   <br> <h2 class="center">What is the Source of Your Sample?</h2><br>
 <div class="card-deck">
      <div class="card"><div class="card-body">

      <p class="card-text">Our lab needs to know what type of sample(s) you are submitting (a.k.a. the “source”) . Add a new source and assign samples to it so we can perform the correct analysis in our laboratory.
    </p><hr>
    <p class="card-text">If you have multiples sources, you may add one source at a time. You can return to this page after you finish registering the first one.</p></div>
    </div>
  
  <div class="card" id="source">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
      <p class="card-title">Human Source</p><br>
      <p class="card-text">•  Collect sample(s) from <b>yourself</b> (e.g. fecal, saliva, skin prick, etc.)<br>
    • Collect sample(s) from <b>someone else</b> (fecal, saliva, skin, prick, etc.)</p>
      <div class="center"><div class="center"><a class="btn btn-primary btn-lg" href="#" role="button">Select</a></div></div>
    </div>
  </div>
  <div class="card" id="source">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
      <p class="card-title">Environmental Source</p><br>
      <p class="card-text">•  Collect sample(s) from a surface (e.g. kitchen counter, backyard soil, food, etc.)</p>
    <div class="center"><a role="button" href="#" class="btn btn-primary btn-lg">Select</a></div>
    </div>
  </div>
  <div class="card" id="source">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
      <p class="card-title">Animal Source</p><br>
      <p class="card-text">•  Collect sample(s) from your pet or an animal (e.g. fecal, oral, skin, etc.)
<br><br>
          <b>This source is currently unavailable.</b></p>
      <div class="center"><a href="#" class="btn btn-secondary btn-lg disabled" tabindex="-1" role="button" aria-disabled="true">Select</a></div>
    </div>
  </div>
</div>

        </div>`


Would also need additional CSS added into the stylesheet to force styles:
`.card-title {
  font-size: 1.125rem;
  font-weight: 700;
}

#source {
  padding-left: 1.5625rem;
  padding-right: 1.5625rem;
  padding-top: 1.875rem;
}`

**Comment by dhakim87** [comment]
Looking at these mockups, it's unclear to me that the user is intending to create a new source.  Maybe we can reword "What is the Source of Your Sample" to indicate that they are creating new sources to assign samples to?  The wording in "Our lab needs to know what type of sample(s) you are submitting (a. k. a. the "source")" seems verbose - Maybe something closer to "Our lab needs to know the source(s) of the sample(s) you are submitting"?

I'll put this page together with the current text, but let's hold off on merging until we're sure the text is finalized.

**Comment by specsdom** [comment]
Ya the title is a bit tricky--originally it was "Add a New Source" but in the designers eyes, that didn't really seem to indicate anything.  Asking a question, we thought, would make participants stop and verify what source they are going to create in order to create a sample

Agreed; now that I'm re-reading that text to myself, it sounds verbose. I'll work on revising it.

**Comment by dhakim87** [comment]
@specsdom Just to quadruple check, the three source icons were created by Departure right, they're not zeplin images?

**Comment by specsdom** [comment]
> @specsdom Just to quadruple check, the three source icons were created by Departure right, they're not zeplin images?

Yup, they were designed by Departures.

**Comment by specsdom** [comment]
For the explainer box, how about this:
"By adding a source to your account and linking samples to it, you will help our lab identify where a sample came from when we receive it.  This helps us perform the correct analysis and provide accurate results.
---
If you plan to take samples from multiple sources, you may add one source at a time.  After you finishing adding the first one, you can return to this page to add more."
