### ISSUE TITLE
New Verification Section

### ISSUE THREAD

**Issue by specsdom** [biocore/microsetta-interface#22]
* Using jumbotron element for verification notice
* Linking to a URL to resend email verification
* As account icon will be in the header, force "View Profile Details" to be unavailable as it would not be viewable at this stage

**Assets**
[Specs on Overall Page](https://zpl.io/2v45RpP)
[Specs on Jumbotron Card](https://zpl.io/25W6P8r)
[Live Preview](https://www.figma.com/proto/xuTVtsQeTAaLxPC6RePkHI/Wireframes-Iteration-1?node-id=9%3A59&viewport=-21574%2C656%2C1&scaling=scale-down)

[Jumbtron](https://getbootstrap.com/docs/4.0/components/jumbotron/)
[Grid (Using a three column grid for bottom text)](https://getbootstrap.com/docs/4.0/layout/grid/)

[Mail+Triple Dots Icon (Custom made; downloadable via Zeplin file)](https://zpl.io/25W6P8r)

**Comment by specsdom** [comment]
I have some of the code to implement the jumbotron, but some elements are missing (no icons, no direct link to resend):
`<div class="jumbotron">
  <h1 class="center">Hello, world!</h1>
  <p class="center">To complete your verification, click on the link in the email AuthRocket has sent to <b>microsetta+3@ucsd.edu</b>. </p>
    <img src="" class="center">
    <h3 class="center">Waiting for you to confirm</h3> <img src="">
  <hr>
  <div class="row">
    <div class="col">
        <p>• Please check both your spam and Inbox
         <br> 
         • AuthRocket is our authentication service
        </p>
    </div>
    <div class="col">
      
    </div>
    <div class="col">
        <p>Is this email wrong? <a href="{{ authrocket_url }}/profile">Update it</a>
         <br> 
            Didn’t received an email? </p></div></div></div>`

One other issue is that since the pull request I have forces the container class to be 0, this forces the jumbotron to be left-aligned instead of centered.  There is a hack-y way to push the jumbotron element to be **almost** centered by adding the following style:
`<div class="jumbotron" style="
    margin-left: 17%;
    width: 100%;
">`

**Comment by wasade** [comment]
This was resolved
