### ISSUE TITLE
Sign Up/Log In Page

### ISSUE THREAD

**Issue by specsdom** [biocore/microsetta-interface#28]
**Assets**
[V1 Screen](https://zpl.io/VDyMPme)
[Live Preview of V1](https://www.figma.com/proto/xuTVtsQeTAaLxPC6RePkHI/Wireframes-Iteration-1?node-id=984%3A15&viewport=783%2C429%2C0.25&scaling=scale-down)
[V2 Screen](https://zpl.io/brwJ9KX) - If integrating the sign up/log in widget isn't something that can be easily/quickly integrated, then let's go with building this version first, then work on integrating the widget later
- Once completed, clicking on the "Sign Up" button can go directly to the sign up page; doesn't need to go to the signup_intermediate page

The "How It Works" image is downloadable directly in the Zeplin files

**Comment by specsdom** [comment]
@AmandaBirmingham

**Comment by AmandaBirmingham** [comment]
@specsdom  I have investigated AuthRocket's customization options and discussed with @dhakim87, and have concluded that, unfortunately, it is not possible to do the V1 Screen.  Visually, AuthRocket allows us to customize ONLY the top-left logo and the color of the submit button.  Additionally, for security purposes, an AuthRocket page cannot be loaded inside an iframe, so it is not possible for us to embed the AuthRocket page within a larger page containing the desired Microsetta chrome. Given this, I will work on setting up the V2 Screen.  

Please specify what you envision happening when the user clicks on the down arrow next to the (I assume?) profile icon ... I do not see that menu's content specified on zeplin, so I cannot scope its feasibility.

**Comment by AmandaBirmingham** [comment]
@specsdom Also, my understanding is that the V2 Screen is what un-logged-in users should see *instead of* the current home page (shown below); is that correct?
<img width="932" alt="Screen Shot 2020-09-10 at 11 50 15 AM" src="https://user-images.githubusercontent.com/10677935/92785093-fcf96e00-f35b-11ea-9947-3a51f0096a06.png">

**Comment by specsdom** [comment]
- Dropdown Menu on this page would show “Sign Up/Log In” options (Dan had accounted for this already so these options should be live if a user isn't logged in)
- V2 is meant to be shown instead of what is currently shown, so your understanding is correct
