### ISSUE TITLE
FFQ Auto-Submits

### ISSUE THREAD

**Issue by specsdom** [biocore/microsetta-interface#45]
Users are reporting that when they open up the FFQ, then step away from their computer for some time, and return, the FFQ automatically submits, and they cannot move forward with answering more questions

When I duplicated this problem, this is what happened:
1.) Opened up FFQ, went to the first question
2.) Let my computer go to screensaver
3.) Returned to my computer and went back to the FFQ
4.) After pressing the next button, I had to disconnect/reconnect to my Wifi since the page wouldn't load (this issue is specific to my laptop though and happens every time it goes idle)
5.) Refreshed the FFQ
6.) Clicked the next button
7.) I was redirected to the Microsetta interface and the FFQ was marked as complete

**Comment by wasade** [comment]
Resolved with updates / addition of the vioscreen registry
