### ISSUE TITLE
Top Food Report does not display properly

### ISSUE THREAD

**Issue by eadiaz73** [biocore/microsetta-interface#76]
As of 2/9/21 a subset of participants are reporting receiving a string of code when clicking on the Top Food Reports button.  I was able to recreate the behavior in one account but obtained the report when clicking on others.

Example 1:

<img width="972" alt="Screen Shot 2021-02-09 at 8 41 53 PM" src="https://user-images.githubusercontent.com/73618446/107599661-1ede7180-6bd6-11eb-9763-615bd753fd59.png">

Example 2 (more code):

"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"utf-8\"/>\n    <title>Microsetta Error Page</title>\n\n    <link rel=\"stylesheet\" href=\"/static/vendor/bootstrap-4.4.1-dist/css/bootstrap.min.css\" />\n    <link rel=\"stylesheet\" href=\"/static/css/minimal_interface.css\" />\n    <style>\n        body {\n            padding-top: 50px;\n            margin: 2%;\n        }\n        .logo-co {\n          width: 200px;\n          height: 36px;\n          object-fit: contain;\n        }\n        .profile-png {\n          width: 24px;\n          height: 24px;\n          object-fit: contain;\n        }\n    </style>\n\n    \n    <script src=\"/static/vendor/js/jquery-3.4.1.min.js\"></script>\n    <script src=\"/static/vendor/js/jquery.validate.min.js\"></script>\n    <script src=\"/static/vendor/bootstrap-4.4.1-dist/js/bootstrap.min.js\"></script>\n    <script src=\"/static/input_util.js\"></script>\n\n    \n\n</head>\n<body>\n    \n    \n    <nav class=\"navbar fixed-top navbar-light bg-light\">\n        <a class=\"navbar-brand\" href=\"https://microsetta.ucsd.edu\" title=\"microsetta.ucsd.edu\">\n            <img src=\"/static/img/logo-co.png\" class=\"logo-co\"/>\n        </a>\n        <div class=\"dropdown show\">\n          <a class=\"btn dropdown-toggle\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n              \n                \n                  stephaniegrutz@gmail.com\n                \n              \n            <img src=\"/static/img/profile.png\" class=\"profile-png\"/>\n          </a>\n\n          <div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"dropdownMenuLink\">\n          \n              \n                <a class=\"dropdown-item\" href=\"/accounts/3a5ee90c-8f80-4d33-95bd-34d6c4352e59/details\">Profile Details</a>\n              \n            <a class=\"dropdown-item\" href=\"https://microsetta-api.ucsd.edu/logout?redirect_uri=https://microsetta-rest.ucsd.edu/logout\">Log Out</a>\n          \n          </div>\n        </div>\n    </nav>\n    \n\n    \n\n    <div class=\"content\">\n\n    \n        <nav aria-label=\"breadcrumb\">\n          <ol class=\"breadcrumb\">\n            <li class=\"breadcrumb-item\"><a href=\"/home\">Home</a></li>\n            \n\n          </ol>\n        </nav>\n    \n        \n        \n       <div class=\"container-fluid\" id=\"app\">\n\n<p>\n    An error seemed to have occurred (see below). It is most likely our fault.\n    We are actively modifying our infrastructure to support COVID-19 research,\n    and we\u2019re still in the process of handling the different type of scenarios\n    that can happen on a website. We apologize for any inconvenience.\n</p>\n<p>\n    If you have any concerns, please email us at <a href=\"mailto:microsetta@ucsd.edu?subject=minimal%20interface%20error&body=%7B%0A%20%20%22detail%22%3A%20%22No%20such%20survey%20recorded%22%2C%0A%20%20%22status%22%3A%20404%2C%0A%20%20%22title%22%3A%20%22Not%20Found%22%2C%0A%20%20%22type%22%3A%20%22about%3Ablank%22%0A%7D%0A\">microsetta@ucsd.edu</a>\n    and please note the error below.\n</p>\n<strong>Error:</strong>\n<br/>\n<pre>{\n  \"detail\": \"No such survey recorded\",\n  \"status\": 404,\n  \"title\": \"Not Found\",\n  \"type\": \"about:blank\"\n}\n</pre>\n\n        </div>\n    </div>\n\n\n    \n    <div>\n        <br />\n        <hr>\n          <p>We will periodically update this site with minor revisions; we\n          apologize if you encounter any temporary inconveniences.</p>\n          \n           <p>\n        \n            Questions?  Check out our <a href=\"/view_faq\" target=\"_blank\">FAQ</a>!</br>\n        \n            Stuck?  Please contact\n            <a href=\"mailto:microsetta@ucsd.edu\">microsetta@ucsd.edu</a>\n            for help.\n        </p>\n    </div> \n    \n</body>\n</html>"

**Comment by wasade** [comment]
Thanks, @eadiaz73! Sent an inquiry to @dhakim87, and we'll begin learning more about what may be going on here

**Comment by wasade** [comment]
PR in, biocore/microsetta-private-api#296

**Comment by wasade** [comment]
fixed previously
